dart-gui: add missing imgui includes
fix:
```cpp
In file included from /build/source/dart/gui/osg/ImGuiWidget.cpp:41:
/build/source/dart/gui/osg/IncludeImGui.hpp:40:12: fatal error: imgui_impl_opengl2.h: No such file or directory
   40 |   #include <imgui_impl_opengl2.h>
      |            ^~~~~~~~~~~~~~~~~~~~~~
```